### ISSUE TITLE
flyekit requires importlib-metadata>=4.0

### ISSUE THREAD

**Issue by asford** [conda-forge/flytekit-feedstock#4]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Upstream package does not specify importlib-metadata as a pinned requirements, however features in the 4.0 release series are required for the standard entrypoints:

Repro trace with importlib-metadata < 4.

This is a little confused, because it looks like `importlib-metadata` and `importlib_metadata` are both present in conda-forge.

```
% python mvp.py 
Traceback (most recent call last):
  File "mvp.py", line 1, in <module>
    from flytekit import task, workflow
  File "/Users/brianmcconeghy/abcd/.conda/lib/python3.8/site-packages/flytekit/__init__.py", line 245, in <module>
    load_implicit_plugins()
  File "/Users/brianmcconeghy/abcd/.conda/lib/python3.8/site-packages/flytekit/__init__.py", line 239, in load_implicit_plugins
    discovered_plugins = entry_points(group="flytekit.plugins")
TypeError: entry_points() got an unexpected keyword argument 'group'
```

**Comment by bmcconeghy** [comment]
Looked into this confusion: The [importlib-metadata repo](https://github.com/conda-forge/importlib-metadata-feedstock) looks like it's archived and read-only, so I'll open a PR to pin `importlib_metadata>=4` as a req.
